import { compile } from "../src/parse";
import * as fs from "fs";

const source = fs.readFileSync(__dirname + "/../src/sample.c", {
  encoding: "utf8",
});
const transpiled = compile(source, []);
console.log(__dirname + "/../src/sample.js");
fs.writeFileSync(
  __dirname + "/../src/sample.js",
  "// Generated by `npm run compile`\n" + transpiled
);

export {};
